const entries=[{"path": "vendor/ort.wasm.min.js", "bytes": 48327}, {"path": "js/detect-worker.js", "bytes": 2011}, {"path": "vendor/ort-wasm-simd-threaded.mjs", "bytes": 20856}, {"path": "vendor/ort-wasm-simd-threaded.wasm", "bytes": 11210254}, {"path": "models/helmet.onnx", "bytes": 38028368}],version='80c0f7fe1a6a6376';
const pending=new Map(),loaded=new Map(),listeners=new Set();
function report(){const total=entries.reduce((n,e)=>n+e.bytes,0),done=[...loaded.values()].reduce((a,b)=>a+b,0);const message=done>=total?'资源已就绪，正在初始化识别引擎…':`正在准备模型 ${Math.min(99,Math.floor(done/total*100))}% · ${(done/1048576).toFixed(1)} / ${(total/1048576).toFixed(1)} MB`;for(const listener of listeners)listener(message);}
async function read(entry){const url=new URL('../'+entry.path,import.meta.url);url.searchParams.set('v',version);let cache;try{cache=await caches.open('helmet-model-'+version);}catch{}
 let response;try{response=await cache?.match(url.href);}catch{}
 if(response){const data=await response.arrayBuffer();if(data.byteLength===entry.bytes){loaded.set(entry.path,data.byteLength);report();return data;}try{await cache.delete(url.href);}catch{}}
 loaded.set(entry.path,0);report();const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),180000);try{response=await fetch(url,{signal:abort.signal});if(!response.ok)throw Error('模型资源下载失败：'+response.status);const chunks=[];let length=0;if(response.body){const reader=response.body.getReader();while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);length+=value.length;loaded.set(entry.path,length);report();}}else{const data=new Uint8Array(await response.arrayBuffer());chunks.push(data);length=data.length;}
 if(length!==entry.bytes)throw Error('模型文件不完整，请检查上传文件后重试');const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}loaded.set(entry.path,length);report();if(cache)cache.put(url.href,new Response(bytes,{headers:{'Content-Type':'application/octet-stream'}})).catch(()=>{});return bytes.buffer;
 }finally{clearTimeout(timer);}}
export async function loadModelAssets(onProgress=()=>{}){listeners.add(onProgress);report();try{return await Promise.all(entries.map(async entry=>{let promise=pending.get(entry.path);if(!promise){promise=read(entry).catch(error=>{pending.delete(entry.path);loaded.delete(entry.path);throw error;});pending.set(entry.path,promise);}const buffer=await promise;return /\.(wasm|onnx)$/.test(entry.path)?buffer.slice(0):new TextDecoder().decode(buffer);}));}finally{listeners.delete(onProgress);}}
export async function preloadModelAssets(){try{await loadModelAssets();}catch{/* A user-triggered attempt can retry a failed download. */}}
