import {buildNotice} from './notice-export.js';
import {renderNoticePreview} from './notice-preview.js';
import {draftHelmetNotice} from './notice-draft.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',undo:'<path d="M3 10h10a7 7 0 0 1 7 7M3 10l5-5M3 10l5 5"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const panel=document.createElement('section');panel.className='task-card notice-card';panel.innerHTML=`<div class="task-title"><h2>整改记录</h2><span id="notice-count">0 个问题</span></div><form id="notice-form" novalidate><div class="notice-grid owner-fields"><label>检查部位<input name="area" required maxlength="60" placeholder="如：1号楼东侧"></label><div class="company-field"><label for="company-entry">责任单位</label><div class="company-control"><div id="company-tags"></div><input id="company-entry" autocomplete="off" placeholder="输入单位，按回车添加" enterkeyhint="done"></div><input name="company" type="hidden"></div><label>整改期限<input id="notice-deadline" type="date" required></label></div><div class="notice-toolbar"><button type="button" id="notice-add" class="primary">＋ 添加照片</button><button type="button" id="notice-records">选取识别记录</button><button type="button" id="notice-info">通知单信息</button><button type="button" id="notice-undo" class="icon-button" aria-label="撤销删除" title="撤销删除" hidden>${icon("undo")}</button></div><div id="notice-choices" hidden></div><div id="notice-issues"></div><div class="notice-toolbar notice-actions"><button type="submit" class="primary">导出 Excel</button><button type="button" id="notice-preview">预览通知单</button></div><p id="notice-status" role="status">添加照片，自动生成问题描述与整改措施。</p><dialog id="notice-info-dialog" class="owner-dialog"><div class="dialog-head"><strong>通知单信息</strong><button type="button" id="notice-info-close" class="icon-button" aria-label="关闭" title="关闭">${icon("close")}</button></div><div class="notice-grid"><label>整改编号<input name="number" required maxlength="32"></label><label>签发日期<input name="date" type="date"></label><label class="wide">项目名称<input name="project" required maxlength="55" value="新余市高铁新区·无人机智慧安全巡检项目"></label><label>检查内容<input name="subject" required maxlength="35" value="安全帽佩戴"></label><label>签发人<input name="issuer" maxlength="24" placeholder="可留空，线下签发"></label></div></dialog><dialog id="notice-edit-dialog" class="owner-dialog"><div class="dialog-head"><strong>问题详情</strong><button type="button" id="notice-edit-close" class="dialog-done" aria-label="完成编辑">${icon("check")}<span>完成</span></button></div><div id="notice-edit-content"></div></dialog><input id="notice-upload" type="file" accept="image/*" multiple hidden></form>`;
$('page-records').prepend(panel);const form=$('notice-form'),issues=[];let removed=null,selected=null;const undo=$('notice-undo');undo.onclick=()=>{if(!removed)return;issues.splice(Math.min(removed.index,issues.length),0,removed.item);removed=null;undo.hidden=true;draw();};
$('notice-info').onclick=()=>$('notice-info-dialog').showModal();$('notice-info-close').onclick=()=>$('notice-info-dialog').close();$('notice-edit-close').onclick=()=>$('notice-edit-dialog').close();
const companies=[];
function syncCompanies(){form.elements.company.value=companies.join('，');$('company-entry').setCustomValidity('');const tags=$('company-tags');tags.replaceChildren();companies.forEach((name,i)=>{if(i){const comma=document.createElement('span');comma.className='company-comma';comma.textContent='，';tags.append(comma);}const chip=document.createElement('span');chip.className='company-chip';const text=document.createElement('span');text.textContent=name;const remove=document.createElement('button');remove.type='button';remove.className='company-remove';remove.setAttribute('aria-label','删除单位：'+name);remove.title='删除单位';remove.innerHTML=icon('close');remove.onclick=()=>{companies.splice(i,1);syncCompanies();draw();};chip.append(text,remove);tags.append(chip);});}
function commitCompany(){const input=$('company-entry');for(const name of input.value.split(/[,，、;；\n]+/).map(x=>x.trim()).filter(Boolean))if(!companies.includes(name))companies.push(name);input.value='';syncCompanies();draw();}
$('company-entry').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();commitCompany();}};
$('company-entry').onblur=()=>{if($('company-entry').value.trim())commitCompany();};
function removeIssue(item){const i=issues.indexOf(item);if(i<0)return;removed={item:issues.splice(i,1)[0],index:i};undo.hidden=false;if(selected===item){selected=null;$('notice-edit-dialog').close();}draw();}
const now=new Date(),localDay=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');form.elements.date.value=localDay;form.elements.number.value=localDay.replaceAll('-','')+'-'+String(now.getHours()).padStart(2,'0')+String(now.getMinutes()).padStart(2,'0');
async function analyze(item){if(item.loading)return;item.loading=true;item.description='';item.measure='';item.error='';draw();$('notice-status').textContent='正在识别照片并生成整改内容…';try{const result=await window.helmetPhotoAI.detectImage(item.original||item.image);if(!issues.includes(item))return;const draft=draftHelmetNotice({count:result.count,area:form.elements.area.value});item.count=result.count;item.image=result.image;if(draft){Object.assign(item,draft);item.origin='根据安全帽识别结果自动生成';$('notice-status').textContent='问题描述与整改措施已自动填写，请核对后导出。';}else{item.error='未检出未带安全帽目标，未生成整改问题。';$('notice-status').textContent=item.error;}}catch(e){item.error='识别未完成：'+e.message;$('notice-status').textContent=item.error;}finally{item.loading=false;draw();}}
async function picture(src){const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas'),scale=Math.min(1,1280/img.naturalWidth);c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return {dataUrl:c.toDataURL('image/jpeg',.88),width:c.width,height:c.height};}
function draw(){const list=$('notice-issues');list.replaceChildren();$('notice-count').textContent=issues.length+' 个问题';issues.forEach((item,i)=>{const row=document.createElement('div');row.className='notice-summary-row';row.innerHTML=`<button type="button" class="notice-summary">${item.image?`<img src="${item.image.dataUrl}" alt="问题照片">`:'<span class="notice-thumb">⌕</span>'}<span class="notice-summary-text"><strong>${i+1}. ${esc(item.loading?'正在识别…':item.description||item.error||'待识别')}</strong><small>${esc(item.company||form.elements.company.value||'待填写责任单位')}</small></span><span class="notice-row-state">${item.loading?'识别中':item.description&&item.measure?'待复核':'待完善'} ›</span></button><button type="button" class="icon-button row-delete" aria-label="删除问题 ${i+1}" title="删除问题">${icon('trash')}</button>`;row.querySelector('.row-delete').onclick=()=>removeIssue(item);row.querySelector('.notice-summary').onclick=()=>{selected=item;drawEditor();$('notice-edit-dialog').showModal();};list.append(row);});if(!issues.length)list.innerHTML='<div class="notice-empty">暂无问题<br><small>添加现场照片，或从识别记录中选取</small></div>';const busy=issues.some(i=>i.loading);$('notice-add').disabled=busy;form.querySelector('[type="submit"]').disabled=busy;if(selected&&issues.includes(selected))drawEditor();}
function drawEditor(){const item=selected;if(!item)return;const box=$('notice-edit-content');box.innerHTML=`<div class="owner-evidence">${item.image?`<img src="${item.image.dataUrl}" alt="现场问题照片">`:''}</div><p class="project-hint">${esc(item.loading?'正在识别…':item.error||item.origin||'请核对识别结果')}</p><label>问题描述<textarea class="problem" rows="2" maxlength="42" ${item.loading?'disabled':''}>${esc(item.description)}</textarea></label><label>规定依据<textarea class="basis" rows="3" maxlength="240" placeholder="填写与本问题相关的规范名称、编号或条款">${esc(item.basis||'')}</textarea></label><label>整改措施<textarea class="measure" rows="2" maxlength="52" ${item.loading?'disabled':''}>${esc(item.measure)}</textarea></label><div class="notice-toolbar"><button type="button" class="reanalyze" ${item.loading?'disabled':''}>重新识别</button><button type="button" class="remove icon-button" aria-label="删除问题" title="删除问题">${icon("trash")}</button></div>`;
for(const [cls,key] of [['problem','description'],['basis','basis'],['measure','measure']])box.querySelector('.'+cls).oninput=e=>{item[key]=e.target.value;};
box.querySelector('.reanalyze').onclick=()=>analyze(item);box.querySelector('.remove').onclick=()=>removeIssue(item);}

$('notice-edit-dialog').addEventListener('close',()=>{selected=null;draw();});
function add(item={}){issues.push({description:'',measure:'',...item});draw();}
$('notice-add').onclick=()=>$('notice-upload').click();
$('notice-upload').onchange=async e=>{const files=[...e.target.files];e.target.value='';for(const file of files){const url=URL.createObjectURL(file);try{const original=await picture(url),item={description:'',measure:'',original,image:original};issues.push(item);await analyze(item);}catch{$('notice-status').textContent='照片读取失败，请换一张照片重试';}finally{URL.revokeObjectURL(url);}}draw();};
form.elements.company.addEventListener('change',draw);draw();
$('notice-records').onclick=()=>{const records=window.helmetRecords?.getEvidence()||[],box=$('notice-choices');box.hidden=!box.hidden;box.replaceChildren();if(!records.length){box.textContent='暂无实际识别证据，可上传现场照片填写。';return;}records.filter(r=>r.review!=='误报').forEach(r=>{const btn=document.createElement('button');btn.type='button';btn.className='notice-choice';const im=document.createElement('img');im.src=r.image;im.alt='识别证据';const tx=document.createElement('span');tx.textContent=`${r.area} · ${r.at} · ${r.review}`;btn.append(im,tx);btn.onclick=async()=>{try{const empty=issues.findIndex(x=>!x.description&&!x.measure&&!x.image);const draft=draftHelmetNotice({count:r.count,area:r.area,review:r.review});if(!draft)throw Error('未检测到安全帽问题');const item={...draft,count:r.count,image:await picture(r.image),origin:`${r.at} · 根据识别结果自动生成 · ${r.review}`};if(empty>=0){issues[empty]=item;draw();}else add(item);box.hidden=true;if(!form.elements.area.value)form.elements.area.value=r.area;}catch{$('notice-status').textContent='证据照片读取失败';}};box.append(btn);});};
function values(){commitCompany();return {...Object.fromEntries(new FormData(form)),deadline:$('notice-deadline').value};}
const dialog=document.createElement('dialog');dialog.className='notice-preview';document.body.append(dialog);
async function makeWorkbook(){const response=await fetch(new URL('../templates/notice.xlsx',import.meta.url));if(!response.ok)throw Error('通知单模板读取失败');return buildNotice(await response.arrayBuffer(),values(),issues,window.JSZip);}
$('notice-preview').onclick=async()=>{dialog.innerHTML=`<header class="notice-preview-head"><strong>通知单预览</strong><button type="button" class="icon-button" aria-label="关闭预览" title="关闭预览">${icon('close')}</button></header><div class="excel-preview-content">正在生成预览…</div>`;dialog.querySelector('button').onclick=()=>dialog.close();dialog.showModal();try{await renderNoticePreview(await makeWorkbook(),window.JSZip,dialog.querySelector('div'));}catch(e){dialog.querySelector('div').textContent=e.message;}};

form.onsubmit=async e=>{e.preventDefault();commitCompany();if(!companies.length){$('company-entry').setCustomValidity('请添加责任单位');$('company-entry').reportValidity();return;}if([...$('notice-info-dialog').querySelectorAll('input')].some(el=>!el.checkValidity())){$('notice-info-dialog').showModal();form.reportValidity();return;}if(!form.reportValidity())return;const v=values();if(issues.some(i=>i.loading)){ $('notice-status').textContent='照片识别中，请稍候';return;}if(issues.some(i=>!i.description.trim()||!i.measure.trim())){$('notice-status').textContent='有照片尚未生成有效整改问题，请重新识别或移除该项';return;}if(!issues.length){$('notice-status').textContent='请添加至少 1 个问题';return;}if(!$('notice-deadline').value){$('notice-status').textContent='请填写整改期限';$('notice-deadline').focus();return;}const button=form.querySelector('[type="submit"]');button.disabled=true;$('notice-status').textContent='正在生成整改通知单…';try{const bytes=await makeWorkbook();const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=`整改通知单-${v.number.replace(/[\\/:*?"<>|]/g,'_')}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('notice-status').textContent='';}catch(e){$('notice-status').textContent=e.message;}finally{button.disabled=false;}};
