import {normalizeZipInput} from './notice-export.js';
export async function renderNoticePreview(bytes,Zip,host){
 const zip=await Zip.loadAsync(await normalizeZipInput(bytes)),parser=new DOMParser(),xml=async name=>parser.parseFromString(await zip.file(name).async('string'),'application/xml'),list=(node,name)=>Array.from(node.getElementsByTagName(name)),text=node=>list(node,'t').map(t=>t.textContent).join(''),styles=await xml('xl/styles.xml'),fonts=list(styles,'fonts')[0].children,xfs=list(styles,'cellXfs')[0].children,shared=list(await xml('xl/sharedStrings.xml'),'si');
 const fontCss=f=>{const get=(tag,attr)=>f?.getElementsByTagName(tag)[0]?.getAttribute(attr);return `font-family:"${get('name','val')||get('rFont','val')||'宋体'}",serif;font-size:${get('sz','val')||11}pt;font-weight:${f?.getElementsByTagName('b').length?'bold':'normal'};font-style:${f?.getElementsByTagName('i').length?'italic':'normal'};text-decoration:${f?.getElementsByTagName('u').length?'underline':'none'};`;};
 const rich=(node,td)=>{const runs=Array.from(node?.children||[]).filter(n=>n.localName==='r');if(runs.length){for(const r of runs){const span=document.createElement('span');span.style.cssText=fontCss(r.getElementsByTagName('rPr')[0]);span.textContent=text(r);td.append(span);}}else td.textContent=node?text(node):'';};
 host.replaceChildren();const sheetFiles=Object.keys(zip.files).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort((a,b)=>parseInt(a.match(/sheet(\d+)/)[1])-parseInt(b.match(/sheet(\d+)/)[1]));
 for(const filename of sheetFiles){const sheet=await xml(filename);if(!list(sheet,'row').length)continue;const section=document.createElement('section');section.className='excel-page';const widths=[80,94,146,114,180];for(const c of list(sheet,'col'))for(let i=+c.getAttribute('min')-1;i<+c.getAttribute('max')&&i<5;i++)widths[i]=Math.floor(+c.getAttribute('width')*7+5);const rows=list(sheet,'row'),heights=rows.map(r=>(+(r.getAttribute('ht')||17))*4/3),table=document.createElement('table');table.style.cssText=`table-layout:fixed;border-collapse:collapse;width:${widths.reduce((a,b)=>a+b,0)}px;`;section.style.cssText=`position:relative;width:${widths.reduce((a,b)=>a+b,0)}px;margin:20px auto;background:white;`;const colgroup=document.createElement('colgroup');widths.forEach(w=>{const c=document.createElement('col');c.style.width=w+'px';colgroup.append(c)});table.append(colgroup);
 const spans=new Map(),covered=new Set();for(const merge of list(sheet,'mergeCell')){const [a,b]=merge.getAttribute('ref').split(':'),x=a.charCodeAt(0)-65,y=+a.slice(1),xx=b.charCodeAt(0)-65,yy=+b.slice(1);spans.set(a,[xx-x+1,yy-y+1]);for(let row=y;row<=yy;row++)for(let col=x;col<=xx;col++)if(row!==y||col!==x)covered.add(String.fromCharCode(65+col)+row);}
 for(const [ri,row] of rows.entries()){const tr=document.createElement('tr');tr.style.height=heights[ri]+'px';for(let ci=0;ci<5;ci++){const ref=String.fromCharCode(65+ci)+(ri+1);if(covered.has(ref))continue;const c=Array.from(row.children).find(c=>c.getAttribute('r')===ref),xf=xfs[+(c?.getAttribute('s')||0)],align=xf?.getElementsByTagName('alignment')[0],td=document.createElement('td'),span=spans.get(ref)||[1,1];td.colSpan=span[0];td.rowSpan=span[1];td.style.cssText=fontCss(fonts[+(xf?.getAttribute('fontId')||0)])+`padding:0 2px;vertical-align:${align?.getAttribute('vertical')==='center'?'middle':align?.getAttribute('vertical')||'bottom'};text-align:${align?.getAttribute('horizontal')||'left'};white-space:pre-wrap;overflow:hidden;line-height:normal;border:${+(xf?.getAttribute('borderId')||0)?'1px solid black':'0'};`;
 const block=document.createElement('div');block.style.cssText=`max-height:${heights.slice(ri,ri+span[1]).reduce((a,b)=>a+b,0)}px;overflow:hidden;`;const node=c?.getAttribute('t')==='s'?shared[+(c.getElementsByTagName('v')[0]?.textContent||0)]:c?.getElementsByTagName('is')[0];rich(node,block);td.append(block);tr.append(td);}table.append(tr);}section.append(table);
 const relfile=filename.replace('worksheets/','worksheets/_rels/')+'.rels';if(zip.file(relfile)){const rel=await xml(relfile),target=list(rel,'Relationship').find(x=>x.getAttribute('Type')?.endsWith('/drawing'))?.getAttribute('Target');if(target){const drawingPath='xl/'+target.replace('../',''),drawing=await xml(drawingPath),drpath=drawingPath.replace('drawings/','drawings/_rels/')+'.rels',dr=await xml(drpath);for(const anchor of list(drawing,'xdr:oneCellAnchor')){const from=anchor.getElementsByTagName('xdr:from')[0],read=name=>+(from.getElementsByTagName('xdr:'+name)[0]?.textContent||0),ext=anchor.getElementsByTagName('xdr:ext')[0],id=anchor.getElementsByTagName('a:blip')[0]?.getAttribute('r:embed'),imageTarget=list(dr,'Relationship').find(r=>r.getAttribute('Id')===id)?.getAttribute('Target');if(!imageTarget)continue;const path='xl/'+imageTarget.replace('../',''),base64=await zip.file(path).async('base64'),img=document.createElement('img');img.src='data:image/'+(path.endsWith('.png')?'png':'jpeg')+';base64,'+base64;img.alt='现场证据照片';img.style.cssText=`position:absolute;left:${widths.slice(0,read('col')).reduce((a,b)=>a+b,0)+read('colOff')/9525}px;top:${heights.slice(0,read('row')).reduce((a,b)=>a+b,0)+read('rowOff')/9525}px;width:${+ext.getAttribute('cx')/9525}px;height:${+ext.getAttribute('cy')/9525}px;max-height:none;object-fit:contain;`;section.append(img);}}}host.append(section);
 }
}
