import * as THREE from '../vendor/three.module.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {planSite,validateSite,FLIGHT_LIMITS} from './site-plan-core.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const panel=document.createElement('section');panel.className='site-import site-workspace';panel.innerHTML=`<div class="site-workspace-head"><div class="site-workspace-title"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 7 9-4 9 4-9 4-9-4Zm0 5 9 4 9-4M3 17l9 4 9-4"/></svg><h2>工地空间态势</h2></div><div class="site-import-actions"><button id="site-demo" type="button" hidden>查看示例工地</button><button id="site-import-model" type="button" class="site-import-button"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Zm0 9 8-4.5M12 12 4 7.5M12 12v9"/></svg><span>导入模型</span></button><button id="site-import-photo" type="button" class="site-import-button"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/></svg><span>导入照片</span></button></div></div><input id="site-model" type="file" accept=".glb,.gltf,.json,.ifc,.rvt" hidden><input id="site-photo" type="file" accept="image/*" hidden><p id="site-status" role="status" hidden></p><input id="site-units" type="hidden" value="1"><input id="site-axis" type="hidden" value="y"><div id="site-editor" hidden><p class="project-hint" id="site-source-note"></p><div class="notice-grid"><label>照片覆盖宽度（米）<input id="site-photo-width" type="number" min="10" max="5000" value="120" disabled></label><label>标注建筑高度（米）<input id="site-height" type="number" min="0" max="500" value="18"></label><label>塔吊 / 避让半径（米）<input id="site-radius" type="number" min="2" max="200" value="15"></label><label>地图标注<select id="site-tool"><option value="none">查看</option><option value="building">巡检区域：点两个对角</option><option value="obstacle">塔吊 / 避让区：点中心</option><option value="takeoff">起飞点：点选位置</option></select></label></div><div class="notice-toolbar"><button data-site-view="follow">跟随无人机</button><button data-site-view="3d">三维视角</button><button data-site-view="top">俯视标注</button></div><div id="site-view" aria-label="导入场地三维示意图"></div><div class="notice-grid"><label>飞行高度（米）<input id="site-altitude" type="number" value="45" min="5" max="120"></label><label>安全净距（米）<input id="site-clearance" type="number" value="5" min="2" max="15"></label><label>巡检间距（米）<input id="site-spacing" type="number" value="8" min="2" max="20"></label><label>飞行速度（米/秒）<input id="site-speed" type="number" value="3" min="1" max="5"></label></div><label class="site-confirm"><input id="site-confirm" type="checkbox">已核对尺寸、起飞点、巡检区域与塔吊避让范围</label><div class="notice-toolbar"><button id="site-plan" class="primary">生成巡检航线</button><button id="site-play" disabled>起飞预演</button><button id="site-export" disabled>保存航线</button></div><p id="site-route-state" role="status">待规划</p><details class="app-disclosure"><summary>区域与避让区</summary><div id="site-objects"></div></details><p class="project-hint">本地坐标航线预演，未接入飞机。实飞需接入定位、地形与 DJI 航线接口并核验现场。</p></div>`;
const demoScene=document.querySelector('.scene-panel');demoScene.before(panel);panel.append(demoScene);const demoHeading=demoScene.querySelector('.panel-heading');const demoViews=demoHeading.querySelector('.view-tabs');panel.querySelector('.site-import-actions').before(demoViews);demoHeading.remove();$('site-import-model').onclick=()=>$('site-model').click();$('site-import-photo').onclick=()=>$('site-photo').click();
let site={buildings:[],obstacles:[],takeoff:{x:0,z:0}},selectedFile=null,photoData=null,photoAspect=1,source='none',first=null,view='3d',plan=null,running=false,segment=0,progress=0,renderer,scene,camera,group,modelObject=null,drone,lineGroup,ground,extent=120,clickMarker;
const num=id=>Number($(id).value),status=t=>{$('site-status').hidden=!t;$('site-status').textContent=t;};
function clearPlan(){plan=null;running=false;$('site-play').disabled=true;$('site-export').disabled=true;$('site-confirm').checked=false;$('site-route-state').textContent='场地已变化，请核对后重新规划';updateImportedFlightInfo();if(lineGroup){scene?.remove(lineGroup);lineGroup.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});lineGroup=null;}}
function disposeObject(obj){obj?.traverse(o=>{o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m){m.map?.dispose();m.dispose();}});}
function init(){if(renderer)return;scene=new THREE.Scene();scene.background=new THREE.Color('#ecf3f6');camera=new THREE.PerspectiveCamera(45,1,.1,30000);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;renderer.toneMappingExposure=1.0;$('site-view').append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0xb4c9d4,1.65));const light=new THREE.DirectionalLight(0xffffff,2.3);light.name='studio-key';light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.bias=-.0003;light.shadow.normalBias=.3;light.shadow.radius=4;scene.add(light.target);const fill=new THREE.DirectionalLight(0xe2edff,0);fill.position.set(-80,60,-60);scene.add(fill);light.position.set(100,180,80);scene.add(light);group=new THREE.Group();scene.add(group);drone=detailedDrone();scene.add(drone);new ResizeObserver(resize).observe($('site-view'));renderer.domElement.addEventListener('pointerdown',mark);installSiteNavigation(renderer.domElement);installOrbitPan(renderer.domElement);installCranePicking(renderer.domElement);let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min(.1,(now-last)/1000);last=now;if($('page-patrol').hidden||$('site-editor').hidden||document.hidden)return;if(running&&plan){let remaining=dt*Math.max(1,num('site-speed'));while(remaining>0&&segment<plan.route.length-1){const a=plan.route[segment],b=plan.route[segment+1],length=Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z),step=Math.min(remaining,length-progress);progress+=step;remaining-=step;const t=length?progress/length:1;drone.position.set(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t+.8,a.z+(b.z-a.z)*t);drone.rotation.y=Math.atan2(b.x-a.x,b.z-a.z);if(progress>=length){segment++;progress=0;}}if(segment>=plan.route.length-1){running=false;$('site-play').textContent='再次预演';$('site-route-state').textContent='已返航降落 · '+plan.distance.toFixed(0)+' 米';}if(view==='follow'){camera.position.lerp(drone.position.clone().add(new THREE.Vector3(extent*.2,extent*.25,extent*.35)),.06);camera.lookAt(drone.position);}}updateImportedFlightInfo();rotatingCranes.forEach(c=>c.rotation.y+=dt*.1);droneRotors.forEach(r=>{if(running)r.rotation.y+=dt*42;});renderer.render(scene,camera);}requestAnimationFrame(animate);}
function resize(){if(!renderer)return;const w=$('site-view').clientWidth,h=$('site-view').clientHeight;if(w<1||h<1)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(!(running&&view==='follow'))setView(view);}
function center(){const pts=site.buildings.concat(site.obstacles,site.takeoff);return new THREE.Vector3(pts.reduce((n,b)=>n+b.x,0)/pts.length,0,pts.reduce((n,b)=>n+b.z,0)/pts.length);}
function setView(mode){view=mode;const bounds=new THREE.Box3();if(photoData){const w=num('site-photo-width');bounds.expandByPoint(new THREE.Vector3(-w/2,0,-w/photoAspect/2));bounds.expandByPoint(new THREE.Vector3(w/2,0,w/photoAspect/2));}for(const b of site.buildings){bounds.expandByPoint(new THREE.Vector3(b.x-b.width/2,0,b.z-b.depth/2));bounds.expandByPoint(new THREE.Vector3(b.x+b.width/2,b.height,b.z+b.depth/2));}for(const o of site.obstacles||[]){bounds.expandByPoint(new THREE.Vector3(o.x-o.radius,0,o.z-o.radius));bounds.expandByPoint(new THREE.Vector3(o.x+o.radius,o.height||0,o.z+o.radius));}bounds.expandByPoint(new THREE.Vector3(site.takeoff.x,0,site.takeoff.z));for(const p of plan?.route||[])bounds.expandByPoint(new THREE.Vector3(p.x,p.y,p.z));const c=bounds.getCenter(new THREE.Vector3()),back=new THREE.Vector3(...(mode==='top'?[0,1,.0001]:[Math.sin(siteOrbitYaw)*Math.cos(siteOrbitPitch),Math.sin(siteOrbitPitch),Math.cos(siteOrbitYaw)*Math.cos(siteOrbitPitch)])).normalize();camera.up.set(0,mode==='top'?0:1,mode==='top'?-1:0);const right=new THREE.Vector3().crossVectors(camera.up,back).normalize(),up=new THREE.Vector3().crossVectors(back,right).normalize(),tanV=Math.tan(camera.fov*Math.PI/360),tanH=tanV*camera.aspect;let distance=5;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const v=new THREE.Vector3(x,y,z).sub(c);distance=Math.max(distance,Math.abs(v.dot(right))/tanH+v.dot(back),Math.abs(v.dot(up))/tanV+v.dot(back));}c.add(sitePan);camera.position.copy(c).addScaledVector(back,distance*1.12);camera.lookAt(c);camera.updateMatrixWorld();panel.querySelectorAll('[data-site-view]').forEach(b=>b.classList.toggle('active',b.dataset.siteView===mode));}
function tag(text,x,y,z){const c=document.createElement('canvas'),g=c.getContext('2d');g.font='500 28px sans-serif';c.width=Math.min(640,Math.max(150,Math.ceil(g.measureText(text).width)+42));c.height=64;g.fillStyle='rgba(255,255,255,.91)';g.beginPath();g.roundRect(2,2,c.width-4,60,13);g.fill();g.strokeStyle='#d2e2e8';g.lineWidth=2;g.stroke();g.fillStyle='#527481';g.font='500 28px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(text,c.width/2,32,c.width-28);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.SpriteMaterial({map:t,depthTest:false,transparent:true}),sprite=new THREE.Sprite(m);sprite.position.set(x,y,z);const h=extent*.012;sprite.scale.set(h*c.width/64,h,1);sprite.renderOrder=8;group.add(sprite);return sprite;}
function studioBox(w,h,d,color,metalness=.2){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,metalness,roughness:.48}));m.castShadow=true;m.receiveShadow=true;return m;}
function studioPlate(w,d,h){const r=Math.min(w,d)*.035,shape=new THREE.Shape();shape.moveTo(-w/2+r,-d/2);shape.lineTo(w/2-r,-d/2);shape.quadraticCurveTo(w/2,-d/2,w/2,-d/2+r);shape.lineTo(w/2,d/2-r);shape.quadraticCurveTo(w/2,d/2,w/2-r,d/2);shape.lineTo(-w/2+r,d/2);shape.quadraticCurveTo(-w/2,d/2,-w/2,d/2-r);shape.lineTo(-w/2,-d/2+r);shape.quadraticCurveTo(-w/2,-d/2,-w/2+r,-d/2);const mesh=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:h,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:h*.16,bevelThickness:h*.16,curveSegments:6}),new THREE.MeshStandardMaterial({color:0xc49b60,metalness:.55,roughness:.36}));mesh.rotation.x=-Math.PI/2;mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}

function facadeMaterial(span,height){const cols=Math.max(1,Math.min(24,Math.floor(span/3.2))),rows=Math.max(1,Math.min(32,Math.round(height/3.2))),c=document.createElement('canvas');c.width=cols*64;c.height=rows*80;const g=c.getContext('2d');g.fillStyle='#bbcbd0';g.fillRect(0,0,c.width,c.height);for(let r=0;r<rows;r++){const y=r*80;g.fillStyle='#f7faf7';g.fillRect(0,y,c.width,9);g.fillStyle='#b1c0c1';g.fillRect(0,y+9,c.width,2);for(let col=0;col<cols;col++){const x=col*64;g.fillStyle='#f8faf7';g.fillRect(x+6,y+20,52,54);g.fillStyle='#a7c4cf';g.fillRect(x+10,y+24,44,45);g.fillStyle='#b6cdd6';g.fillRect(x+13,y+27,17,38);g.fillStyle='#d1dfe1';g.fillRect(x+31,y+24,2,45);g.fillStyle='#a4b7bd';g.fillRect(x+9,y+69,46,3);}}const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map:texture,roughness:.73,metalness:.04});}
function architecturalBuilding(w,h,d){const out=new THREE.Group(),rim=Math.min(.45,h*.1),wallHeight=Math.max(.08,h-rim),plain=new THREE.MeshStandardMaterial({color:0xf1f5f1,roughness:.82}),front=facadeMaterial(w,h),side=facadeMaterial(d,h);const body=new THREE.Mesh(new THREE.BoxGeometry(w,wallHeight,d),[side,side,plain,plain,front,front]);body.position.y=wallHeight/2;body.castShadow=true;body.receiveShadow=true;out.add(body);const roof=studioBox(w*.98,.04,d*.98,0xeaf0ed,0);roof.position.y=wallHeight;out.add(roof);const edge=Math.min(.22,w*.035,d*.035);for(const [bw,bd,x,z] of [[w,edge,0,-d/2+edge/2],[w,edge,0,d/2-edge/2],[edge,d-2*edge,-w/2+edge/2,0],[edge,d-2*edge,w/2-edge/2,0]]){const parapet=studioBox(bw,rim,bd,0xf4f7f3,0);parapet.position.set(x,h-rim/2,z);out.add(parapet);}const nx=Math.min(12,Math.max(1,Math.floor(w/5))),nz=Math.min(12,Math.max(1,Math.floor(d/5)));if(h>2){const columns=new THREE.InstancedMesh(new THREE.BoxGeometry(edge*.6,rim*.7,edge*.6),new THREE.MeshStandardMaterial({color:0xa8babd,roughness:.8}),nx*nz);let i=0;const matrix=new THREE.Matrix4();for(let ix=0;ix<nx;ix++)for(let iz=0;iz<nz;iz++){matrix.makeTranslation(-w/2+w*(ix+.5)/nx,wallHeight+rim*.35,-d/2+d*(iz+.5)/nz);columns.setMatrixAt(i++,matrix);}columns.castShadow=true;out.add(columns);}return out;}
const areaNames={building:'房屋',pit:'基坑作业区',shed:'钢筋加工区',yard:'材料堆场',office:'项目部'};
let rotatingCranes=[],droneRotors=[];
function modelBeam(parent,a,b,r,color){const va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,va.distanceTo(vb),5),new THREE.MeshStandardMaterial({color,roughness:.75}));m.position.copy(va).add(vb).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),vb.sub(va).normalize());m.castShadow=true;parent.add(m);return m;}
function modelBox(parent,w,h,d,x,y,z,color){const m=studioBox(w,h,d,color,0);m.position.set(x,y,z);parent.add(m);return m;}
function regionModel(b){const {width:w,depth:d,height:h}=b,type=b.type||'building';if(type==='building'||type==='office'){const g=architecturalBuilding(w,Math.max(.5,h),d);if(type==='office')modelBox(g,w*.99,.18,d*.99,0,h+.05,0,0x6fa4b3);return g;}const g=new THREE.Group();if(type==='pit'){const dep=b.excavationDepth||3,wall=Math.min(.45,w*.03,d*.03);modelBox(g,w,.15,d,0,-dep,0,0xc4c6b6);for(const x of [-w/2,w/2])modelBox(g,wall,dep,d,x,-dep/2,0,0xa7b8b9);for(const z of [-d/2,d/2])modelBox(g,w,dep,wall,0,-dep/2,z,0xa7b8b9);for(let i=1;i<9;i++){modelBeam(g,[-w/2+i*w/9,-dep+.15,-d/2],[-w/2+i*w/9,-dep+.15,d/2],.035,0x7a9198);modelBeam(g,[-w/2,-dep+.15,-d/2+i*d/9],[w/2,-dep+.15,-d/2+i*d/9],.035,0x7a9198);}for(const z of [-d/2,d/2]){modelBeam(g,[-w/2,.9,z],[w/2,.9,z],.05,0xd9b36a);for(let i=0;i<=8;i++)modelBeam(g,[-w/2+i*w/8,0,z],[-w/2+i*w/8,1,z],.04,0x839ba0);}return g;}
modelBox(g,w,.12,d,0,.06,0,0xdbe4e2);
if(type==='shed'){for(const x of [-w*.46,w*.46])for(const z of [-d*.45,0,d*.45])modelBox(g,.25,h,.25,x,h/2,z,0x9eafb0);modelBox(g,w,.2,d,0,h,0,0x72a7ba);for(let i=0;i<12;i++)modelBeam(g,[-w/2+i*w/11,h+.12,-d/2],[-w/2+i*w/11,h+.12,d/2],.045,0xb3d1dc);for(let j=0;j<3;j++)for(let i=0;i<5;i++)modelBeam(g,[-w*.3,.4+j*.17,-d*.25+i*.3],[w*.3,.4+j*.17,-d*.25+i*.3],.09,0x687d82);
}else{for(let i=0;i<3;i++)for(let j=0;j<3;j++){const stack=Math.min(h||1.5,1+i*.2);modelBox(g,w*.19,stack,d*.19,(i-1)*w*.29,stack/2+.12,(j-1)*d*.28,0xa4b2ab);}}return g;}
function craneModel(o){const g=new THREE.Group(),h=o.height||30,r=o.radius,half=Math.max(.45,r*.035);for(const x of [-half,half])for(const z of [-half,half])modelBeam(g,[x,0,z],[x,h,z],.09,0xd3a652);for(let y=0;y<h;y+=h/12)for(const z of [-half,half])modelBeam(g,[-half,y,z],[half,Math.min(h,y+h/12),z],.05,0xe5b866);const arm=new THREE.Group();arm.position.y=h;g.add(arm);modelBox(arm,r*1.3,.3,half*1.6,r*.35,0,0,0xe7b760);for(let i=0;i<12;i++)modelBeam(arm,[-r*.3+i*r*1.3/12,.1,0],[-r*.3+(i+1)*r*1.3/12,1,0],.065,0xe4b05b);modelBeam(arm,[-r*.3,1,0],[r,1,0],.1,0xecc57b);modelBox(arm,r*.13,1,half*2,-r*.2,-.5,0,0x8fa3aa);modelBeam(arm,[r*.72,0,0],[r*.72,-h*.65,0],.035,0x7d9197);g.position.set(o.x,0,o.z);rotatingCranes.push(arm);g.userData.crane=o;return g;}
function detailedDrone(){const g=new THREE.Group();modelBox(g,1.3,.5,1.8,0,0,0,0x47616d);modelBox(g,1.1,.15,1.4,0,.3,0,0xedf3f4);for(const x of [-1.7,1.7])for(const z of [-1.5,1.5]){modelBeam(g,[0,0,0],[x,.12,z],.1,0x526e7c);const rotor=new THREE.Group();rotor.position.set(x,.3,z);modelBox(rotor,2,.05,.13,0,0,0,0x748c96);g.add(rotor);droneRotors.push(rotor);}modelBox(g,.45,.45,.5,0,-.4,-.65,0x23414e);for(const x of [-.7,.7])modelBeam(g,[x,-.6,-.8],[x,-.6,.8],.07,0x526e7c);return g;}
function siteGround(w,d){const slab=Math.max(.7,Math.min(w,d)*.009),shape=new THREE.Shape();const edge=Math.max(2,Math.min(w,d)*.09);shape.moveTo(-w/2-edge,-d/2-edge);shape.lineTo(w/2+edge,-d/2-edge);shape.lineTo(w/2+edge,d/2+edge);shape.lineTo(-w/2-edge,d/2+edge);shape.closePath();for(const b of site.buildings.filter(b=>b.type==='pit')){const x=b.x,z=-b.z,hw=b.width/2,hd=b.depth/2;if(Math.abs(x)+hw>w/2||Math.abs(z)+hd>d/2)continue;const hole=new THREE.Path();hole.moveTo(x-hw,z-hd);hole.lineTo(x-hw,z+hd);hole.lineTo(x+hw,z+hd);hole.lineTo(x+hw,z-hd);hole.closePath();shape.holes.push(hole);}const ground=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:slab,bevelEnabled:false}),[new THREE.MeshStandardMaterial({color:0xe0e5e4,roughness:1}),new THREE.MeshStandardMaterial({color:0xc8d6dc,roughness:1})]);ground.rotation.x=-Math.PI/2;ground.position.y=-slab;ground.receiveShadow=true;group.add(ground);const road=Math.max(2,Math.min(w,d)*.07);for(const z of [-d/2-road/2,d/2+road/2]){modelBox(group,w+2*road,.12,road,0,-.05,z,0xb7c6ce);for(let x=-w/2;x<w/2;x+=Math.max(4,w/18))modelBox(group,1.5,.02,.08,x,.03,z,0xf8fcfd);}for(const x of [-w/2-road/2,w/2+road/2])modelBox(group,road,.12,d,x,-.05,0,0xb7c6ce);for(const z of [-d/2-road,d/2+road]){modelBox(group,w+road*2,.7,.2,0,.3,z,0x94b3be);for(let i=0;i<16;i++){const x=-w/2+w*i/15,tree=new THREE.Mesh(new THREE.SphereGeometry(Math.min(1.3,road*.27),7,5),new THREE.MeshStandardMaterial({color:0x96b8ad,roughness:1}));tree.position.set(x,1,z);tree.castShadow=true;group.add(tree);}}const grid=new THREE.GridHelper(Math.max(w,d)*3,80,0xd4e2e8,0xdfebef);grid.position.y=-Math.max(5,...site.buildings.map(b=>b.excavationDepth||0))-.5;group.add(grid);}

function refresh(){ensureCraneIds();init();rotatingCranes=[];clearPlan();for(const c of [...group.children]){group.remove(c);if(c!==modelObject)disposeObject(c);}if(modelObject)group.add(modelObject);const b=site.buildings;extent=Math.max(60,photoData?num('site-photo-width'):0,...b.map(x=>Math.max(Math.abs(x.x)*2+x.width,Math.abs(x.z)*2+x.depth,x.height*2)),...site.obstacles.map(x=>Math.max(Math.abs(x.x),Math.abs(x.z))*2+x.radius*2))*1.15;
 const key=scene.getObjectByName('studio-key');key.position.set(-extent*.5,extent,extent*.31);const shadowSpan=extent;Object.assign(key.shadow.camera,{left:-shadowSpan,right:shadowSpan,top:shadowSpan,bottom:-shadowSpan,near:1,far:extent*5});key.shadow.camera.updateProjectionMatrix();
 const boardW=photoData?num('site-photo-width'):extent,boardD=photoData?boardW/photoAspect:extent*.85,thickness=Math.max(.18,extent*.003);
 siteGround(boardW,boardD);siteRoadDetails(boardW,boardD);
 for(const x of b){if(!modelObject){const model=regionModel(x);model.position.set(x.x,0,x.z);group.add(model);}tag(x.name,x.x,Math.max(0,x.height)+extent*.016,x.z);}
 for(const o of site.obstacles){const ring=new THREE.Mesh(new THREE.RingGeometry(o.radius-.1,o.radius+.1,64),new THREE.MeshBasicMaterial({color:0xd6b975,transparent:true,opacity:.45,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(o.x,.05,o.z);group.add(ring);if(o.kind==='crane')group.add(craneModel(o));const label=tag(o.kind==='crane'?craneName(o):'避让区',o.x,(o.height||0)+2,o.z);if(o.kind==='crane')label.userData.crane=o;}

 const pad=new THREE.Mesh(new THREE.CylinderGeometry(3.5,3.5,.2,40),new THREE.MeshBasicMaterial({color:0x487f77}));pad.position.set(site.takeoff.x,.15,site.takeoff.z);group.add(pad);tag('起飞点',site.takeoff.x,4,site.takeoff.z);drone.position.set(site.takeoff.x,.8,site.takeoff.z);
 $('site-editor').hidden=false;demoViews.hidden=true;document.querySelector('.scene-panel').hidden=true;$('site-demo').hidden=false;$('site-demo').textContent='查看示例工地';setView(view);resize();objects();photoUI();updateCraneManager();}
function objects(){const list=$('site-objects');list.replaceChildren();for(const [type,array] of [['building',site.buildings],['obstacle',site.obstacles]])array.forEach((x,i)=>{const row=document.createElement('div');row.className='site-object';row.innerHTML=`<span>${esc(type==='building'?x.name:'避让区 '+(i+1))}</span><label>${type==='building'?'高度':'半径'}<input type="number" min="${type==='building'?0:2}" max="500" value="${type==='building'?x.height:x.radius}"></label><button type="button">移除</button>`;row.querySelector('input').onchange=e=>{const value=Number(e.target.value);if(!Number.isFinite(value)||value<0)return;x[type==='building'?'height':'radius']=value;refresh();};row.querySelector('button').onclick=()=>{array.splice(i,1);refresh();};list.append(row);});}
function mark(e){const tool=$('site-tool').value;if(tool==='none'||view!=='top')return;const rect=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const p=new THREE.Vector3();if(!ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p))return;const point={x:Math.round(p.x*10)/10,z:Math.round(p.z*10)/10};if(tool==='takeoff'){site.takeoff=point;refresh();}else if(tool==='obstacle'){const radius=num('site-radius');if(!(radius>=2))return;site.obstacles.push({...point,radius});refresh();}else if(!first){first=point;status('已标记第一角，请点区域对角');}else{const width=Math.abs(point.x-first.x),depth=Math.abs(point.z-first.z);if(width<1||depth<1){first=null;status('区域过小，请重新标注');return;}site.buildings.push({name:'巡检区域 '+(site.buildings.length+1),x:(point.x+first.x)/2,z:(point.z+first.z)/2,width,depth,height:Math.max(0,num('site-height'))});first=null;refresh();status('已生成建筑示意与巡检范围');}}
$('site-tool').onchange=()=>{first=null;if($('site-tool').value!=='none')setView('top');};panel.querySelectorAll('[data-site-view]').forEach(b=>b.onclick=()=>setView(b.dataset.siteView));
function resetSource(){nextCraneId=1;sitePan.set(0,0,0);siteOrbitYaw=.58;siteOrbitPitch=.62;if(camera){camera.zoom=1;camera.updateProjectionMatrix();}clearPlan();if(modelObject){group?.remove(modelObject);disposeObject(modelObject);modelObject=null;}photoData=null;site={buildings:[],obstacles:[],takeoff:{x:0,z:0}};first=null;}
function modelTargets(obj){const targets=[];obj.updateMatrixWorld(true);const children=obj.children.length>1?obj.children:(obj.children[0]?.children.length>1?obj.children[0].children:[obj]);for(const [i,node] of children.entries()){const box=new THREE.Box3().setFromObject(node);if(box.isEmpty())continue;const size=box.getSize(new THREE.Vector3()),c=box.getCenter(new THREE.Vector3());if(size.x<1||size.z<1||size.y<1)continue;targets.push({name:node.name||'模型区域 '+(i+1),x:c.x,z:c.z,width:size.x,depth:size.z,height:Math.max(0,box.max.y)});}if(!targets.length)throw Error('未找到有效建筑区域，请检查单位与方向');return targets;}
async function loadModel(file){if(file.size>80*1024*1024)throw Error('模型超过 80MB，请先按楼栋轻量化');const ext=file.name.split('.').at(-1).toLowerCase();if(ext==='json'){const json=JSON.parse(await file.text()),valid=validateSite(json);resetSource();site=valid;source='json';$('site-source-note').textContent='已读取本地米制坐标；请核对巡检区域、起飞点及障碍物。';refresh();return;}
 if(!['glb','gltf'].includes(ext))throw Error('暂时无法读取该模型，请联系建模人员提供适用于网页展示的模型文件。');const buffer=await file.arrayBuffer();let data;if(ext==='glb'){const dv=new DataView(buffer);if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw Error('仅支持 glTF 2.0');const len=dv.getUint32(12,true);data=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,len)).trim());}else data=JSON.parse(new TextDecoder().decode(buffer));
 if((data.extensionsRequired||[]).some(x=>/draco|meshopt|basisu/i.test(x)))throw Error('请导出未使用 Draco / Meshopt / KTX 压缩的 GLB');if([...(data.buffers||[]),...(data.images||[])].some(x=>x.uri&&!x.uri.startsWith('data:')))throw Error('请将纹理和几何内嵌后导出 GLB，暂不加载外部文件');
 const loader=new GLTFLoader();const gltf=await loader.parseAsync(ext==='glb'?buffer:JSON.stringify(data),'');const obj=gltf.scene;obj.scale.setScalar(num('site-units'));if($('site-axis').value==='z')obj.rotation.x=-Math.PI/2;obj.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(obj);if(box.isEmpty())throw Error('模型没有可显示的几何');const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());if(Math.max(size.x,size.z)>5000||Math.max(size.x,size.z)<2)throw Error('模型尺寸异常，请联系建模人员核对尺寸后重新导入。');obj.position.sub(new THREE.Vector3(center.x,box.min.y,center.z));obj.updateMatrixWorld(true);const buildings=modelTargets(obj);resetSource();modelObject=obj;site={buildings,obstacles:[],takeoff:{x:-size.x/2-15,z:-size.z/2-15}};source='model';$('site-source-note').textContent='已按模型分组提取候选巡检范围。请移除地面等非巡检项，补充塔吊完整回转避让区并核对尺寸。';refresh();}
$('site-model').onchange=async e=>{const f=e.target.files[0];if(!f)return;selectedFile=f;status('正在读取模型…');try{await loadModel(f);$('site-photo-width').disabled=true;status(f.name+' · 已生成场景');}catch(e){status(e.message);}};
$('site-photo').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const url=URL.createObjectURL(f);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth<400||img.naturalHeight<300)throw Error('照片过小，请选择清晰的工地俯视图');const c=document.createElement('canvas'),scale=Math.min(1,2000/img.naturalWidth);c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);pendingPhoto={data:c.toDataURL('image/jpeg',.9),aspect:c.width/c.height,file:f};$('photo-gate-image').src=pendingPhoto.data;$('photo-overhead-confirm').checked=false;photoGate.showModal();}catch(e){status('照片读取失败：'+e.message);}finally{URL.revokeObjectURL(url);}};
let oldWidth=120;$('site-photo-width').onchange=()=>{const width=num('site-photo-width');if(!(width>=10&&width<=5000)){status('覆盖宽度需在 10—5000 米之间');return;}const ratio=width/oldWidth;site.buildings.forEach(b=>{b.x*=ratio;b.z*=ratio;b.width*=ratio;b.depth*=ratio;});site.obstacles.forEach(o=>{o.x*=ratio;o.z*=ratio;o.radius*=ratio;});site.takeoff.x*=ratio;site.takeoff.z*=ratio;oldWidth=width;refresh();};
for(const id of ['site-altitude','site-clearance','site-spacing'])$(id).onchange=clearPlan;
$('site-plan').onclick=()=>{try{if(source==='photo'){if(!photoCalibration)throw Error('请完成控制点坐标校准');if(!site.buildings.length)throw Error('请先画出至少一栋建筑');if(site.buildings.some(b=>!(b.type==='pit'?b.excavationDepth>0:b.height>0)))throw Error('请点击待填写区域，补全建筑高度');if(!photoTakeoffSet)throw Error('请先在照片上设置起飞点');}if(!$('site-confirm').checked)throw Error('请先核对并勾选场地尺寸与避让范围');plan=planSite(site,{spacing:num('site-spacing'),clearance:num('site-clearance'),altitude:num('site-altitude'),speed:num('site-speed')});if(lineGroup){scene.remove(lineGroup);disposeObject(lineGroup);}lineGroup=new THREE.Group();const dashMatrices=[],up=new THREE.Vector3(0,1,0);for(let i=1;i<plan.route.length;i++){const a=plan.route[i-1],b=plan.route[i],from=new THREE.Vector3(a.x,a.y,a.z),to=new THREE.Vector3(b.x,b.y,b.z),delta=to.clone().sub(from),length=delta.length();if(length<.01)continue;const rotation=new THREE.Quaternion().setFromUnitVectors(up,delta.clone().normalize());for(let d=0;d<length;d+=3.4){const end=Math.min(d+2.5,length),position=from.clone().addScaledVector(delta,(d+end)/2/length);dashMatrices.push(new THREE.Matrix4().compose(position,rotation,new THREE.Vector3(1,end-d,1)));}}if(dashMatrices.length){const dashes=new THREE.InstancedMesh(new THREE.CylinderGeometry(.19,.19,1,6),new THREE.MeshBasicMaterial({color:'#4289be',transparent:true,opacity:.8}),dashMatrices.length);dashMatrices.forEach((matrix,i)=>dashes.setMatrixAt(i,matrix));dashes.instanceMatrix.needsUpdate=true;lineGroup.add(dashes);}scene.add(lineGroup);$('site-play').disabled=false;$('site-export').disabled=false;running=false;segment=0;progress=0;$('site-play').textContent='起飞预演';$('site-route-state').textContent=`无交叉闭环 · ${plan.route.length} 航点 · ${plan.distance.toFixed(0)} 米 · 高度 ${plan.altitude.toFixed(1)} 米`;status(plan.restrictedLength>0?'航线已生成，塔身附近部分巡检线已跳过':'航线已生成 · 高于塔臂 · 闭环返航');updateImportedFlightInfo();if(source==='photo'){photoPreview=true;$('photo-preview-toggle').textContent='返回标注';photoUI();setView('3d');resize();}}catch(e){plan=null;running=false;$('site-play').disabled=true;$('site-export').disabled=true;if(lineGroup){scene.remove(lineGroup);disposeObject(lineGroup);lineGroup=null;}$('site-route-state').textContent=e.message;}};
$('site-play').onclick=()=>{if(!plan)return;if(segment>=plan.route.length-1){segment=0;progress=0;}running=!running;$('site-play').textContent=running?'暂停预演':'继续预演';};
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('site-export').onclick=()=>{if(plan)download({schema:'helmet-route/v1',coordinateSystem:'local-meters',origin:'model-local-origin',previewOnly:true,source,controlPoints:source==='photo'?controlPoints:[],coordinateMapping:source==='photo'?photoCalibration:null,speed:num('site-speed'),clearance:num('site-clearance'),site:plan.site,coverage:{restrictedLength:plan.restrictedLength,skippedRegions:plan.skippedRegions,visitedRegions:plan.visitedRegions},waypoints:plan.route},'巡检航线-本地坐标.json');};
$('site-demo').onclick=()=>{running=false;const showImported=$('site-editor').hidden;$('site-editor').hidden=!showImported;demoViews.hidden=showImported;demoScene.hidden=showImported;$('site-demo').textContent=showImported?'查看示例工地':'返回我的场地';if(showImported){photoUI();resize();}$('site-play').textContent=plan?'继续预演':'起飞预演';window.dispatchEvent(new Event('resize'));};

// Photo plan: measured overhead image, direct drawing and height editing.
const photoGate=document.createElement('dialog');photoGate.className='owner-dialog';photoGate.innerHTML=`<div class="dialog-head"><strong>导入工地俯视图</strong><button type="button" class="icon-button" aria-label="关闭">×</button></div><p class="project-hint">仅使用垂直向下拍摄的工地全景或正射图。</p><img id="photo-gate-image" alt="待导入的工地俯视图" style="width:100%;max-height:220px;object-fit:contain"><form id="photo-gate-form"><label class="photo-check"><input id="photo-overhead-confirm" type="checkbox" required>这是工地俯视图</label><p class="project-hint">斜拍、地面照片不适用；此处由导入人确认。</p><button class="dialog-done" type="submit">开始标注</button></form>`;document.body.append(photoGate);photoGate.querySelector('button').onclick=()=>photoGate.close();
let pendingPhoto=null,photoMode='building',photoTakeoffSet=false,photoDrag=null,photoSelected=null,photoPreview=false;
const photoControls=document.createElement('div');photoControls.id='photo-tools';photoControls.hidden=true;photoControls.innerHTML=`<div class="photo-steps"><strong>拖框划区域，选择模型类型</strong><span id="photo-building-count"></span></div><div class="photo-tool-row"><button type="button" data-photo-tool="building" class="active">▧ 画区域</button><button type="button" data-photo-tool="takeoff">⌖ 起飞点</button><button type="button" data-photo-tool="crane">塔吊</button><button type="button" id="photo-control-button">⌗ 控制点</button><span id="photo-radius-label" hidden><input id="photo-obstacle-radius" type="hidden" value="15"></span><button type="button" id="photo-preview-toggle">查看三维</button></div><div id="photo-map"><svg id="photo-map-svg" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="工地俯视图，拖动绘制建筑区域"><image id="photo-map-image" x="0" y="0" width="1000" height="1000" preserveAspectRatio="none"/><g id="photo-map-shapes"></g><rect id="photo-drag-box" visibility="hidden"/></svg><div id="photo-labels"></div></div><p id="photo-map-hint">按住鼠标拖出矩形，松开完成；点击矩形设置高度。</p>`;
$('site-source-note').after(photoControls);const flightSettings=document.createElement('details');flightSettings.className='app-disclosure photo-flight-settings';flightSettings.innerHTML='<summary>飞行参数</summary>';const flightGrid=$('site-altitude').closest('.notice-grid');flightGrid.before(flightSettings);flightSettings.append(flightGrid);
const heightDialog=document.createElement('dialog');heightDialog.className='owner-dialog photo-height-dialog';heightDialog.innerHTML=`<div class="dialog-head"><strong>区域设置</strong><button type="button" class="icon-button" aria-label="关闭">×</button></div><form id="photo-height-form"><label>区域类型<select id="photo-region-type"><option value="building">房屋</option><option value="pit">基坑作业区</option><option value="shed">钢筋加工区</option><option value="yard">材料堆场</option><option value="office">项目部</option></select></label><label>区域名称<input id="photo-building-name" maxlength="30" required></label><label><span id="region-height-label">高度（米）</span><input id="photo-building-height" type="number" min="0.5" max="500" step="any" placeholder="输入实际高度" required></label><p id="photo-building-size" class="project-hint"></p><div class="notice-toolbar"><button type="submit" class="primary">生成模型</button><button type="button" id="photo-building-delete">删除区域</button></div></form>`;document.body.append(heightDialog);heightDialog.querySelector('button').onclick=()=>heightDialog.close();
function photoPoint(e){const r=$('photo-map-svg').getBoundingClientRect();return {x:Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),y:Math.max(0,Math.min(1000,(e.clientY-r.top)/r.height*1000))};}
function photoWorld(p){const w=num('site-photo-width');return {x:(p.x/1000-.5)*w,z:(p.y/1000-.5)*w/photoAspect};}
function photoRect(a,b){const p=photoWorld(a),q=photoWorld(b);return {x:(p.x+q.x)/2,z:(p.z+q.z)/2,width:Math.abs(p.x-q.x),depth:Math.abs(p.z-q.z)};}
function photoUI(){const active=source==='photo';panel.classList.toggle('photo-workflow',active);photoControls.hidden=!active;$('site-photo-width').closest('.notice-grid').hidden=active;$('site-source-note').hidden=active;const views=$('site-view').previousElementSibling;views.hidden=active&&!photoPreview;$('site-view').hidden=active&&!photoPreview;photoControls.querySelector('#photo-map').hidden=photoPreview;$('photo-map-hint').hidden=photoPreview;$('site-objects').closest('details').hidden=active;if(active)drawPhoto();}
function drawPhoto(){if(source!=='photo')return;const w=num('site-photo-width'),d=w/photoAspect;const xp=x=>(x/w+.5)*1000,zp=z=>(z/d+.5)*1000;
$('photo-map').style.aspectRatio=String(photoAspect);$('photo-map').style.setProperty('--photo-aspect',photoAspect);$('photo-map-image').setAttribute('href',photoData);
$('photo-map-shapes').innerHTML=site.buildings.map((b,i)=>`<g class="photo-building ${b.height>0||b.type==='pit'?'':'pending'}" data-building="${i}" tabindex="0" role="button" aria-label="${esc(b.name)}，${b.height?b.height+'米':'待填写高度'}"><rect x="${xp(b.x-b.width/2)}" y="${zp(b.z-b.depth/2)}" width="${b.width/w*1000}" height="${b.depth/d*1000}"/><text x="${xp(b.x)}" y="${zp(b.z)}" text-anchor="middle">${esc(b.name)} · ${b.height?b.height+'m':'填高度'}</text></g>`).join('')+site.obstacles.map((o,i)=>`<g class="photo-obstacle" data-obstacle="${i}" tabindex="0" role="button" aria-label="${o.kind==='crane'?esc(craneName(o))+'，点击编辑':'删除避让区 '+(i+1)}"><ellipse cx="${xp(o.x)}" cy="${zp(o.z)}" rx="${o.radius/w*1000}" ry="${o.radius/d*1000}"/><text x="${xp(o.x)}" y="${zp(o.z)}" text-anchor="middle">避让区 ×</text></g>`).join('')+(photoTakeoffSet?`<g class="photo-takeoff"><circle cx="${xp(site.takeoff.x)}" cy="${zp(site.takeoff.z)}" r="13"/><text x="${xp(site.takeoff.x)}" y="${zp(site.takeoff.z)-21}" text-anchor="middle">起飞点</text></g>`:'');
drawPhotoLabels();$('photo-building-count').textContent=`${site.buildings.length} 个区域 · ${photoTakeoffSet?'已设起飞点':'请设置起飞点'}`;
$('photo-map-shapes').querySelectorAll('[data-building]').forEach(el=>{const open=()=>openHeight(site.buildings[+el.dataset.building]);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};});
$('photo-map-shapes').querySelectorAll('[data-obstacle]').forEach(el=>{const remove=()=>{site.obstacles.splice(+el.dataset.obstacle,1);refresh();};el.onkeydown=e=>{if(e.key==='Delete')remove();};});
}
function openHeight(b){if(!b)return;photoSelected=b;$('photo-region-type').value=b.type||'building';$('region-height-label').textContent=b.type==='pit'?'开挖深度（米）':'高度（米）';$('photo-building-size').textContent=photoCalibration?'平面尺寸 '+b.width.toFixed(2)+' × '+b.depth.toFixed(2)+' 米':'平面尺寸待控制点校准';$('photo-building-name').value=b.name;$('photo-building-height').value=(b.type==='pit'?b.excavationDepth:b.height)||'';heightDialog.showModal();$('photo-building-height').focus();}
$('photo-height-form').onsubmit=e=>{e.preventDefault();if(!$('photo-height-form').reportValidity()||!photoSelected)return;photoSelected.name=$('photo-building-name').value.trim()||'建筑';photoSelected.type=$('photo-region-type').value;const amount=Number($('photo-building-height').value);photoSelected.height=photoSelected.type==='pit'?0:amount;photoSelected.excavationDepth=photoSelected.type==='pit'?amount:0;heightDialog.close();refresh();status('区域模型已生成，可继续标注或规划航线');};
$('photo-building-delete').onclick=()=>{const i=site.buildings.indexOf(photoSelected);if(i>=0)site.buildings.splice(i,1);heightDialog.close();refresh();};
photoControls.querySelectorAll('[data-photo-tool]').forEach(button=>button.onclick=()=>{photoMode=button.dataset.photoTool;if(photoPreview){photoPreview=false;photoUI();}$('photo-preview-toggle').textContent='查看三维';photoControls.querySelectorAll('[data-photo-tool]').forEach(b=>b.classList.toggle('active',b===button));$('photo-radius-label').hidden=photoMode!=='obstacle';$('photo-map-hint').textContent={building:'拖动绘制矩形；点击区域填写或修改高度。',takeoff:'在空旷位置点击，设置无人机起飞与返航点。',obstacle:'点击设置避让范围；短按已有避让区可删除。',crane:'点击放置塔吊，再设置高度和回转半径。'}[photoMode];});
$('photo-preview-toggle').onclick=()=>{photoPreview=!photoPreview;$('photo-preview-toggle').textContent=photoPreview?'返回标注':'查看三维';photoUI();if(photoPreview){setView('3d');resize();}};
const photoSvg=$('photo-map-svg');
photoSvg.onpointerdown=e=>{if(e.button!==0||photoDrag)return;e.preventDefault();const p=photoPoint(e);if(photoMode==='control'){pickControl(p);return;}if(photoMode==='crane'){const hit=e.target.closest('[data-obstacle]'),existing=hit&&site.obstacles[Number(hit.dataset.obstacle)];if(existing?.kind==='crane'){openCrane(existing,false);return;}openCrane({...photoWorld(p),kind:'crane',height:30,radius:15},true);return;}if(photoMode==='takeoff'){site.takeoff=photoWorld(p);photoTakeoffSet=true;refresh();status('起飞点已设置');return;}if(photoMode==='obstacle'){const radius=num('photo-obstacle-radius');if(!Number.isFinite(radius)||radius<2||radius>200){$('photo-obstacle-radius').reportValidity();return;}site.obstacles.push({...photoWorld(p),radius});refresh();return;}photoDrag={start:p,id:e.pointerId,target:e.target.closest('[data-building],[data-obstacle]')};photoSvg.setPointerCapture(e.pointerId);const box=$('photo-drag-box');for(const [key,value] of Object.entries({x:p.x,y:p.y,width:0,height:0,visibility:'visible'}))box.setAttribute(key,value);};
photoSvg.onpointermove=e=>{if(!photoDrag||e.pointerId!==photoDrag.id)return;const p=photoPoint(e),a=photoDrag.start,box=$('photo-drag-box');for(const [k,v] of Object.entries({x:Math.min(p.x,a.x),y:Math.min(p.y,a.y),width:Math.abs(p.x-a.x),height:Math.abs(p.y-a.y)}))box.setAttribute(k,v);};
function stopPhotoDrag(){photoDrag=null;$('photo-drag-box').setAttribute('visibility','hidden');}
photoSvg.onpointerup=e=>{if(!photoDrag||photoDrag.id!==e.pointerId)return;const a=photoDrag.start,target=photoDrag.target,p=photoPoint(e),screen=photoSvg.getBoundingClientRect(),dx=Math.abs(p.x-a.x)*screen.width/1000,dy=Math.abs(p.y-a.y)*screen.height/1000;stopPhotoDrag();if(photoSvg.hasPointerCapture(e.pointerId))photoSvg.releasePointerCapture(e.pointerId);if(dx<5&&dy<5){if(target?.dataset.building!==undefined)openHeight(site.buildings[+target.dataset.building]);else if(target?.dataset.obstacle!==undefined){const ob=site.obstacles[+target.dataset.obstacle];if(ob.kind==='crane')openCrane(ob,false);else{site.obstacles.splice(+target.dataset.obstacle,1);refresh();}}return;}const r=photoRect(a,p);if(dx<5||dy<5||r.width<.1||r.depth<.1){status('区域太小，请重新拖框');return;}site.buildings.push({...r,name:'建筑 '+(site.buildings.length+1),height:0,type:'building'});refresh();openHeight(site.buildings.at(-1));status('选择区域类型，填写高度或开挖深度');};photoSvg.onpointercancel=stopPhotoDrag;photoSvg.onlostpointercapture=stopPhotoDrag;
$('photo-gate-form').onsubmit=e=>{e.preventDefault();if(!$('photo-gate-form').reportValidity()||!pendingPhoto)return;resetSource();controlPoints=[];photoCalibration=null;$('control-form').reset();$('control-result').textContent='';for(const i of [0,1])$('control-position-'+i).textContent='未选点';photoData=pendingPhoto.data;photoAspect=pendingPhoto.aspect;selectedFile=pendingPhoto.file;source='photo';$('site-photo-width').value=120;oldWidth=num('site-photo-width');$('site-photo-width').disabled=false;photoTakeoffSet=false;photoPreview=false;photoMode='building';$('photo-preview-toggle').textContent='查看三维';photoControls.querySelectorAll('[data-photo-tool]').forEach(b=>b.classList.toggle('active',b.dataset.photoTool==='building'));$('photo-radius-label').hidden=true;site.takeoff={x:0,z:0};photoGate.close();refresh();status('先用控制点校准尺寸，再拖框标建筑');pendingPhoto=null;showControls();};
let controlPoints=[],photoCalibration=null,controlPick=null;
function drawPhotoLabels(){const w=num('site-photo-width'),d=w/photoAspect;const label=(x,y,t,kind='')=>`<span class="photo-label ${kind}" style="left:${x}%;top:${y}%">${esc(t)}</span>`;$('photo-labels').innerHTML=site.buildings.map(b=>label((b.x/w+.5)*100,(b.z/d+.5)*100,`${b.name} · ${b.type==='pit'?'深 '+b.excavationDepth+' m':b.height?b.height+' m':'待设置'}`)).join('')+site.obstacles.map(o=>label((o.x/w+.5)*100,(o.z/d+.5)*100,o.kind==='crane'?craneName(o):'避让区 ×','danger').replace('<span ',o.kind==='crane'?`<span role="button" tabindex="0" data-crane-id="${o.craneId}" `:'<span ')).join('')+(photoTakeoffSet?label((site.takeoff.x/w+.5)*100,(site.takeoff.z/d+.5)*100,'● 起飞点','takeoff'):'')+controlPoints.map((p,i)=>p?label(p.pixel.x/10,p.pixel.y/10,'⊕ P'+(i+1),'control'):'').join('');}
const controlDialog=document.createElement('dialog');controlDialog.className='owner-dialog';controlDialog.innerHTML=`<div class="dialog-head"><strong>控制点校准</strong><button type="button" class="icon-button" aria-label="关闭">×</button></div><p class="project-hint">在图上选两个相距较远的已知点，填写同一平面坐标系的实测坐标（米）。</p><form id="control-form">${[0,1].map(i=>`<div class="control-point-row"><button type="button" data-pick-control="${i}">选取 P${i+1}</button><span id="control-position-${i}">未选点</span><label>X / 东坐标（米）<input id="control-x-${i}" type="number" step="any" required></label><label>Y / 北坐标（米）<input id="control-y-${i}" type="number" step="any" required></label></div>`).join('')}<p id="control-result" role="status"></p><button type="submit" class="primary">校准尺寸</button></form><p class="project-hint">不填经纬度。两点校准适用于等比例俯视图，不能消除斜拍畸变。</p>`;document.body.append(controlDialog);controlDialog.querySelector('button').onclick=()=>controlDialog.close();
function showControls(){controlPoints.forEach((p,i)=>{if(p){$('control-position-'+i).textContent='已选 P'+(i+1);if(p.x!==undefined)$('control-x-'+i).value=p.x;if(p.y!==undefined)$('control-y-'+i).value=p.y;}});controlDialog.showModal();}
$('photo-control-button').onclick=()=>{if(photoPreview){photoPreview=false;photoUI();$('photo-preview-toggle').textContent='查看三维';}showControls();};
controlDialog.querySelectorAll('[data-pick-control]').forEach(b=>b.onclick=()=>{controlPick=+b.dataset.pickControl;photoMode='control';controlDialog.close();$('photo-map-hint').textContent='请在图上点击控制点 P'+(controlPick+1);});
function pickControl(p){controlPoints[controlPick]={...controlPoints[controlPick],pixel:p};photoCalibration=null;clearPlan();photoMode='building';drawPhoto();showControls();}
function solvePhotoCalibration(points,aspect){const [a,b]=points;if(!a||!b)throw Error('请先选取 P1、P2');const px=(b.pixel.x-a.pixel.x)/1000,py=-(b.pixel.y-a.pixel.y)/1000/aspect,dx=b.x-a.x,dy=b.y-a.y,span=Math.hypot(px,py),distance=Math.hypot(dx,dy);if(![px,py,dx,dy].every(Number.isFinite)||span<.03||distance<.1)throw Error('控制点太近或坐标无效，请重新选择');const width=distance/span;if(width<10||width>5000)throw Error('校准宽度超出 10—5000 米，请检查坐标单位');const angle=Math.atan2(dy,dx)-Math.atan2(py,px),cos=Math.cos(angle),sin=Math.sin(angle),lx=(a.pixel.x/1000-.5)*width,ly=-(a.pixel.y/1000-.5)*width/aspect;return {width,rotationRadians:angle,origin:{x:a.x-cos*lx+sin*ly,y:a.y-sin*lx-cos*ly},units:'meters',axes:'worldX=origin.x+cos(angle)*local.x+sin(angle)*local.z; worldY=origin.y+sin(angle)*local.x-cos(angle)*local.z'};}
$('control-form').onsubmit=e=>{e.preventDefault();if(!$('control-form').reportValidity())return;try{const points=[0,1].map(i=>({pixel:controlPoints[i]?.pixel,x:Number($('control-x-'+i).value),y:Number($('control-y-'+i).value)}));if(points.some(p=>!p.pixel))throw Error('请先在图片中选取两个控制点');const calibrated=solvePhotoCalibration(points,photoAspect);$('site-photo-width').value=calibrated.width;$('site-photo-width').onchange();controlPoints=points;photoCalibration=calibrated;drawPhoto();$('control-result').textContent='校准完成 · 图片宽度 '+calibrated.width.toFixed(2)+' 米';status('已按控制点校准尺寸，请重新生成巡检航线');controlDialog.close();}catch(error){$('control-result').textContent=error.message;}};
$('photo-region-type').onchange=()=>{const type=$('photo-region-type').value;$('region-height-label').textContent=type==='pit'?'开挖深度（米）':type==='yard'?'堆放高度（米）':'高度（米）';if(!photoSelected||/^建筑 \d+$/.test($('photo-building-name').value)||Object.values(areaNames).includes($('photo-building-name').value))$('photo-building-name').value=areaNames[type];};
let nextCraneId=1;
function ensureCraneIds(){const seen=new Set();for(const o of site.obstacles){if(o.kind!=='crane')continue;if(Number.isSafeInteger(o.craneId)&&o.craneId>0&&!seen.has(o.craneId)){seen.add(o.craneId);nextCraneId=Math.max(nextCraneId,o.craneId+1);}else o.craneId=null;}for(const o of site.obstacles)if(o.kind==='crane'&&!o.craneId)o.craneId=nextCraneId++;}
function craneName(o){return '塔吊 '+o.craneId;}
const craneTrashIcon='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></svg>';
const craneDialog=document.createElement('dialog');craneDialog.className='owner-dialog photo-height-dialog';craneDialog.innerHTML=`<div class="dialog-head"><strong>塔吊设置</strong><button type="button" class="icon-button" aria-label="关闭">×</button></div><form id="crane-form"><label>塔吊高度（米）<input id="crane-height" type="number" min="5" max="200" step="any" required></label><label>回转半径（米）<input id="crane-radius" type="number" min="2" max="100" step="any" required></label><p class="project-hint">航线根据塔吊高度与回转半径规划，并预留安全净距。</p><div class="notice-toolbar"><button type="submit" class="primary">保存塔吊</button><button type="button" id="crane-delete" class="icon-button crane-delete-button" aria-label="删除塔吊" title="删除塔吊">${craneTrashIcon}</button></div></form>`;document.body.append(craneDialog);let editingCrane=null,newCrane=false;craneDialog.querySelector('button').onclick=()=>craneDialog.close();function openCrane(o,fresh){ensureCraneIds();craneDialog.querySelector('strong').textContent=fresh?'新增塔吊':craneName(o)+' · 设置';editingCrane=o;newCrane=fresh;$('crane-height').value=o.height;$('crane-radius').value=o.radius;$('crane-delete').hidden=fresh;craneDialog.showModal();}$('crane-form').onsubmit=e=>{e.preventDefault();if(!$('crane-form').reportValidity())return;editingCrane.height=num('crane-height');editingCrane.radius=num('crane-radius');if(newCrane){editingCrane.craneId=nextCraneId++;site.obstacles.push(editingCrane);}craneDialog.close();refresh();};$('crane-delete').onclick=()=>{const i=site.obstacles.indexOf(editingCrane);if(i>=0)site.obstacles.splice(i,1);craneDialog.close();refresh();};
function zoomSite(factor){if(!camera)return;camera.zoom=THREE.MathUtils.clamp(camera.zoom*factor,.45,4);camera.updateProjectionMatrix();}
function installSiteNavigation(canvas){const controls=document.createElement('div');controls.className='site-nav-controls';controls.innerHTML='<button type="button" aria-label="放大模型" title="放大">＋</button><button type="button" aria-label="缩小模型" title="缩小">−</button><button type="button" aria-label="恢复全景" title="恢复全景">⌖</button>';$('site-view').append(controls);const [plus,minus,reset]=controls.children;plus.onclick=()=>zoomSite(1.2);minus.onclick=()=>zoomSite(1/1.2);reset.onclick=()=>{camera.zoom=1;siteOrbitYaw=.58;siteOrbitPitch=.62;sitePan.set(0,0,0);camera.updateProjectionMatrix();setView(view);};canvas.addEventListener('wheel',e=>{e.preventDefault();zoomSite(Math.exp(-e.deltaY*.001));},{passive:false});const pointers=new Map();let distance=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];distance=Math.hypot(a.x-b.x,a.y-b.y);}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],next=Math.hypot(a.x-b.x,a.y-b.y);if(distance>5)zoomSite(next/distance);distance=next;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);distance=0;});}
const craneManager=document.createElement('dialog');craneManager.className='owner-dialog';craneManager.innerHTML='<div class="dialog-head"><strong>塔吊管理</strong><button type="button" class="icon-button" aria-label="关闭">×</button></div><div id="site-crane-list"></div>';document.body.append(craneManager);craneManager.querySelector('button').onclick=()=>craneManager.close();const craneManageButton=document.createElement('button');craneManageButton.type='button';craneManageButton.id='site-crane-manage';craneManageButton.textContent='塔吊管理';$('site-view').previousElementSibling.append(craneManageButton);craneManageButton.onclick=()=>{updateCraneManager();craneManager.showModal();};const photoCraneManageButton=craneManageButton.cloneNode(true);photoCraneManageButton.id='photo-crane-manage';photoControls.querySelector('.photo-tool-row').append(photoCraneManageButton);photoCraneManageButton.onclick=craneManageButton.onclick;
function updateCraneManager(){const cranes=site.obstacles.filter(o=>o.kind==='crane');craneManageButton.textContent=photoCraneManageButton.textContent='塔吊管理 · '+cranes.length;const list=$('site-crane-list');list.replaceChildren();if(!cranes.length){list.textContent='暂无塔吊，可在照片标注页点击“塔吊”放置。';return;}cranes.forEach((o,i)=>{const row=document.createElement('div');row.className='crane-manage-row';row.innerHTML=`<div><strong>${esc(craneName(o))}</strong><small>高度 ${o.height} m · 回转半径 ${o.radius} m</small></div><button type="button" class="crane-edit">编辑</button><button type="button" class="crane-remove icon-button crane-delete-button" aria-label="删除${esc(craneName(o))}" title="删除${esc(craneName(o))}">${craneTrashIcon}</button>`;row.querySelector('.crane-edit').onclick=()=>{craneManager.close();openCrane(o,false);};row.querySelector('.crane-remove').onclick=()=>{site.obstacles.splice(site.obstacles.indexOf(o),1);refresh();updateCraneManager();status('塔吊已删除，请重新生成航线');};list.append(row);});}
function siteRoadDetails(w,d){const road=Math.max(3,Math.min(w,d)*.045),color=0xb7c6ce;function roadStrip(x,z,rw,rd,vertical){modelBox(group,rw,.06,rd,x,.03,z,color);const len=vertical?rd:rw,step=Math.max(5,len/35);for(let t=-len/2+step/2;t<len/2;t+=step)modelBox(group,vertical?.08:step*.36,.025,vertical?step*.36:.08,x+(vertical?0:t),.08,z+(vertical?t:0),0xf5fafb);for(const side of [-1,1])modelBox(group,vertical?.18:rw,.14,vertical?rd:.18,x+(vertical?side*rw/2:0),.09,z+(vertical?0:side*rd/2),0xeaf2f3);}
function corridors(axis,max){const intervals=site.buildings.map(b=>{const center=b[axis],span=axis==='x'?b.width:b.depth;return [center-span/2-road*.3,center+span/2+road*.3];}).sort((a,b)=>a[0]-b[0]),gaps=[];let edge=-max/2;for(const [a,b] of intervals){if(a-edge>road*1.4)gaps.push([edge,a]);edge=Math.max(edge,b);}if(max/2-edge>road*1.4)gaps.push([edge,max/2]);return gaps.sort((a,b)=>(b[1]-b[0])-(a[1]-a[0])).slice(0,2);}
for(const [a,b] of corridors('x',w))roadStrip((a+b)/2,0,road,d,true);for(const [a,b] of corridors('z',d))roadStrip(0,(a+b)/2,w,road,false);const outer=Math.max(2,Math.min(w,d)*.07);for(const x of [-w/2-outer/2,w/2+outer/2])roadStrip(x,0,outer,d,true);for(const z of [-d/2-outer/2,d/2+outer/2])roadStrip(0,z,w+outer*2,outer,false);for(const x of [-w/2-outer,w/2+outer]){modelBox(group,.2,.7,d, x,.3,0,0x94b3be);const count=Math.max(4,Math.min(24,Math.floor(d/10)));for(let i=0;i<=count;i++){const tree=new THREE.Mesh(new THREE.SphereGeometry(Math.min(1.3,outer*.27),7,5),new THREE.MeshStandardMaterial({color:0x96b8ad,roughness:1}));tree.position.set(x,1,-d/2+d*i/count);tree.castShadow=true;group.add(tree);}}}
let siteOrbitYaw=.58,siteOrbitPitch=.62;const sitePan=new THREE.Vector3();
function installOrbitPan(canvas){let drag=null;const touches=new Set();canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if($('site-tool').value!=='none'&&view==='top'&&source!=='photo')return;touches.add(e.pointerId);if(touches.size>1){drag=null;return;}drag={id:e.pointerId,x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey||view==='top'};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id||touches.size!==1)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!dx&&!dy)return;if(view==='follow')view='3d';if(drag.pan){const scale=extent/Math.max(200,canvas.clientWidth)/camera.zoom,right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1);sitePan.addScaledVector(right,-dx*scale*1.5).addScaledVector(up,dy*scale*1.5);}else{siteOrbitYaw-=dx*.006;siteOrbitPitch=THREE.MathUtils.clamp(siteOrbitPitch+dy*.006,.2,1.4);}drag.x=e.clientX;drag.y=e.clientY;setView(view);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,e=>{touches.delete(e.pointerId);if(drag?.id===e.pointerId)drag=null;});}
const flightInfo=document.createElement('section');flightInfo.className='imported-flight-info scene-support';flightInfo.innerHTML='<div class="drone-info"><div class="drone-title"><strong>DJI</strong><span>巡检无人机 01</span><span class="pill">模拟在线</span></div><div class="telemetry"><span>相对高度<b id="imported-height">— <small>m</small></b></span><span>巡航速度<b id="imported-speed">0.0 <small>m/s</small></b></span><span>电量<b title="尚未接入无人机电量">—<small>%</small></b></span><span>巡检进度<b id="imported-progress">0<small>%</small></b></span></div><div class="progress-track"><i id="imported-progress-bar" style="width:0%"></i></div></div>';$('site-view').after(flightInfo);flightInfo.after(flightSettings);const importedRouteDetails=document.createElement('details');importedRouteDetails.className='app-disclosure imported-route-details';importedRouteDetails.innerHTML='<summary>巡检航线</summary><div class="route-panel"><div class="route-title"><strong>巡检航线 <span>01</span></strong><span id="imported-drone-state">待规划</span></div><div class="imported-route-summary"><span id="imported-route-summary">设置场地后生成巡检航线</span><span>预计飞行 <b id="imported-time">—</b></span></div><div id="imported-route-stops" class="route-stops"></div></div>';flightSettings.after(importedRouteDetails);
// photoUI uses the view toolbar immediately before site-view, which remains in place.
const envelopeButton=document.createElement('button');envelopeButton.type='button';envelopeButton.textContent='安全包络';envelopeButton.setAttribute('aria-pressed','true');envelopeButton.className='active';const parameterHeading=document.createElement('div');parameterHeading.className='settings-heading';parameterHeading.innerHTML='<strong>飞行参数</strong>';const parameterActions=document.createElement('div');parameterActions.append(envelopeButton);const replanButton=document.createElement('button');replanButton.type='button';replanButton.textContent='⤳ 重新规划';replanButton.onclick=()=>$('site-plan').click();parameterActions.append(replanButton);parameterHeading.append(parameterActions);flightGrid.before(parameterHeading);let droneEnvelope=null,envelopeVisible=true;envelopeButton.onclick=()=>{envelopeVisible=!envelopeVisible;envelopeButton.classList.toggle('active',envelopeVisible);envelopeButton.setAttribute('aria-pressed',String(envelopeVisible));if(droneEnvelope)droneEnvelope.visible=envelopeVisible;};let flightInfoLast=0;
function updateImportedFlightInfo(){if(!$('imported-drone-state'))return;const now=performance.now();if(running&&now-flightInfoLast<200)return;flightInfoLast=now;if(drone&&!droneEnvelope){droneEnvelope=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),new THREE.MeshBasicMaterial({color:0x799df2,wireframe:true,transparent:true,opacity:.18,depthWrite:false}));drone.add(droneEnvelope);}if(droneEnvelope){droneEnvelope.scale.setScalar(Math.max(2,num('site-clearance')));droneEnvelope.visible=envelopeVisible;}
let traveled=0;if(plan){for(let i=1;i<=Math.min(segment,plan.route.length-1);i++){const a=plan.route[i-1],b=plan.route[i];traveled+=Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);}traveled+=progress;}const finished=!!plan&&segment>=plan.route.length-1,percent=plan?Math.min(100,Math.round(traveled/plan.distance*100)):0;$('imported-drone-state').textContent=!plan?'待规划':finished?'DJI · 已降落':!running?'DJI · 已暂停':segment===0?'DJI · 垂直起飞':segment===plan.route.length-2?'DJI · 降落':'DJI · 巡检中';$('imported-height').innerHTML=(plan?Math.max(0,(drone?.position.y||.8)-.8).toFixed(1):'—')+' <small>m</small>';$('imported-speed').innerHTML=(running?num('site-speed').toFixed(1):'0.0')+' <small>m/s</small>';$('imported-progress').innerHTML=percent+'<small>%</small>';$('imported-progress-bar').style.width=percent+'%';$('imported-time').textContent=plan?(plan.distance/Math.max(1,num('site-speed'))/60).toFixed(1)+' min':'—';$('imported-route-summary').textContent=plan?`航线 ${plan.distance.toFixed(0)} m · 航高 ${plan.altitude.toFixed(1)} m · 安全净距 ${num('site-clearance')} m`+(plan.restrictedLength>0?` · 受限巡检线 ${plan.restrictedLength.toFixed(1)} m 未覆盖`:'')+(plan.skippedRegions.length?' · 未覆盖区域：'+plan.skippedRegions.join('、'):''):'设置场地后生成巡检航线';const routeKey=plan?plan.visitedRegions.join('|'):'none';if(flightInfo.dataset.routeKey!==routeKey){flightInfo.dataset.routeKey=routeKey;$('imported-route-stops').innerHTML=plan?['起飞点',...plan.visitedRegions,'返航降落'].map((name,i)=>'<span class="stop"><i>'+ (i===0||i===plan.visitedRegions.length+1?'H':String(i).padStart(2,'0'))+'</i>'+esc(name)+'</span>').join(''):'';}}
const siteGestureHint=document.createElement('p');siteGestureHint.className='site-gesture-hint';siteGestureHint.textContent='拖动旋转 · 右键 / Shift 拖动平移 · 滚轮或双指缩放';$('site-view').after(siteGestureHint);
for(const [id,label,unit] of [['site-altitude','目标航高','m'],['site-clearance','安全净距','m'],['site-speed','飞行速度','m/s'],['site-spacing','巡检间距','m']]){const input=$(id),limit=FLIGHT_LIMITS[id.replace('site-','')];input.min=limit.min;input.max=limit.max;input.value=limit.default;const wrapper=input.closest('label'),title=document.createElement('span'),output=document.createElement('output');title.className='imported-setting-title';title.textContent=label;output.textContent=input.value+' '+unit;title.append(output);for(const node of [...wrapper.childNodes])if(node!==input)node.remove();wrapper.prepend(title);input.type='range';input.step=id==='site-speed'?'.5':'1';input.addEventListener('input',()=>{output.textContent=input.value+' '+unit;});}

function installCranePicking(canvas){let start=null;const pointers=new Set();canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);start=pointers.size===1&&e.button===0?{id:e.pointerId,x:e.clientX,y:e.clientY}:null;});canvas.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)start=null;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;});canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);const hit=start;start=null;if(!hit||hit.id!==e.pointerId||Math.hypot(e.clientX-hit.x,e.clientY-hit.y)>5||($('site-tool').value!=='none'&&view==='top'&&source!=='photo'))return;const rect=canvas.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),camera);for(const intersection of ray.intersectObjects(group.children,true)){let object=intersection.object;while(object&&object!==group){if(object.userData.crane){openCrane(object.userData.crane,false);return;}object=object.parent;}}});}

function selectCraneLabel(e){const label=e.target.closest('[data-crane-id]');if(!label)return;const crane=site.obstacles.find(o=>o.kind==='crane'&&o.craneId===Number(label.dataset.craneId));if(crane){e.preventDefault();e.stopPropagation();openCrane(crane,false);}}
$('photo-labels').addEventListener('click',selectCraneLabel);
$('photo-labels').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')selectCraneLabel(e);});
